name: jupyter-env
channels:
    - conda-forge
    - bioconda
    - r
dependencies:
    - numpy
    - scipy
    - pandas
    - matplotlib
    - biopython
    - jupyter
    - jupyterlab
    - r-essentials
    - rpy2
    - ipywidgets
    - nodejs
 
